layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  behance: givonaldoc2cf7
  facebook: gilvonaldoc
  instagram: gilvonaldo_cavalcanti
  linkedin: gilvonaldocavalcanti/
  stackoverflow: 12178768/gilvonaldo-a-s-cavalcanti
  telegram: gilvonaldo
  twitter: gilvonaldoc
  youtube: channel/UCkXKu4NPZDQU-AhCcGK1m1A

# Links disponíveis em: https://devicon.dev/

topics:
  - name: Python
    web_url: https://www.python.org/
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg

  - name: Java
    web_url: https://www.oracle.com/br/java/
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg

  - name: Django
    web_url: https://www.djangoproject.com/
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-original.svg

  - name: JavaScript
    web_url: https://www.javascript.com/
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg

  - name: Flutter
    web_url: https://flutter.dev/
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg

  - name: Android
    web_url: https://www.android.com/intl/pt-BR_br/
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg
