layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  behance: givonaldoc2cf7
  facebook: gilvonaldoc
  instagram: gilvonaldo_cavalcanti
  linkedin: gilvonaldocavalcanti/
  stackoverflow: 12178768/gilvonaldo-a-s-cavalcanti
  telegram: gilvonaldo
  twitter: gilvonaldoc
  youtube: channel/UCkXKu4NPZDQU-AhCcGK1m1A?view_as=subscriber

topics:
  - name: Django
    web_url: https://www.djangoproject.com/
    image_url: https://symbols.getvecta.com/stencil_78/77_django.fffc5e761b.svg

  - name: Ionic
    web_url: https://ionicframework.com/
    image_url: https://symbols.getvecta.com/stencil_25/60_ionic.0adad41642.svg

  - name: Flutter
    web_url: https://flutter.io/
    image_url: https://symbols.getvecta.com/stencil_80/63_flutter-icon.dec5447e22.svg

  - name: Angular
    web_url: https://angular.io/
    image_url: https://symbols.getvecta.com/stencil_25/9_angular.bd98f4bded.svg
